# Only for test on docker desktop !!! WARNING !!!
# This file is only for testing on docker desktop, it is not used in the production environment.
version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
# be.api:
#     image: beapi
#     container_name: be-api
#     build:
#         context: .
#         dockerfile: Dockerfile
#     environment:
#         - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
#         - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_EXPORTER_OTLP_PROTOCOL}
#     networks:
#         - backend

# be.mysql:
#     image: mysql:latest
#     container_name: BE.MySQL
#     environment:
#         - MYSQL_DATABASE=${MYSQL_DATABASE}
#         - MYSQL_USER=${MYSQL_USER}
#         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#     ports:
#         - 3307:3306
#     networks:
#         - backend

# seq:
#     image: datalust/seq:latest
#     container_name: be-seq
#     environment:
#         - ACCEPT_EULA=Y
#     ports:
#         - 5341:5341 # Logging
#         - 8081:80 # Web UI run on port 8081
#     networks:
#         - backend

# elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
#     container_name: be-elasticsearch
#     environment:
#         - discovery.type=single-node
#         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ports:
#         - 9200:9200
#     networks:
#         - backend

# kibana:
#     image: docker.elastic.co/kibana/kibana:7.10.2
#     container_name: be-kibana
#     environment:
#         - ELASTICSEARCH_HOSTS=http://be-elasticsearch:9200
#     ports:
#         - 5601:5601
#     networks:
#         - backend

networks:
  backend:
    driver: bridge
