services:
  userservice.api:
    image: ${DOCKER_REGISTRY-}userserviceapi
    build:
      context: .
      dockerfile: src/UserService.API/Dockerfile

  productservice.api:
    image: ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: src/ProductService.API/Dockerfile


  paymentservice.api:
    image: ${DOCKER_REGISTRY-}paymentserviceapi
    build:
      context: .
      dockerfile: src/PaymentService.API/Dockerfile


  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: src/OrderService.API/Dockerfile


  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: src/Gateway.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - userservice.api
      - productservice.api
      - paymentservice.api
      - orderservice.api

